### ISSUE TITLE
DevOps: Set up this app on Kubernetes

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/quackstack#13]
Once we've got #9 under control, we need to get it deployed to the PyDis stack, probably in the Kubernetes stack. That probably means someone needs to set up a kubernetes manifest inside https://github.com/python-discord/kubernetes.

Maybe @jb3 will contribute to this, or someone else on the @python-discord/devops team.

**Comment by ks129** [comment]
QuackStack has been deployed to Kubernetes.
