### ISSUE TITLE
Put all the necessary quackstack assets into the branding repo.

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/quackstack#2]
In order to procedurally generate ducks, we need duck templates and accessories.

Currently, these are available in https://github.com/python-discord/aaaaAAAA/tree/main/assets/duck-builder, and should be copied over into the branding repo.

We also need to decide on a way to access these resources from within this repo. Two options are:
- Use GitHub API calls. This is how we do it at https://github.com/python-discord/bot, I believe.
- Add branding as a submodule in this repo.

**Comment by Akarys42** [comment]
Submodules sucks, we would have to manually bump it in this repo when branding is updated. API calls could work, what about downloading the zip of the branding repo during build and decompress it?

**Comment by jb3** [comment]
Downloading a ZIP during build sounds fine, but maybe a background task in quackstack itself is a better idea? That way we don't have to redeploy every time we want to get new assets in.

I'm not of the opinion that submodules suck, per se, but I think that for a repository that is as active as branding and the want to have new assets live on quackstack immediately it does present a bit of a problem that we need to manually bump here.

**Comment by Akarys42** [comment]
Right now we use a submodule. I think it is better to switch it to a zip download though, what do you think?

The idea of a background task is interesting, but I'd still like to inject it into the image to avoid downloading it every time the image is pulled.

**Comment by jb3** [comment]
Having to rebuild the whole image when we update assets is not an ideal solution though.

Maybe we should use only API calls to the branding repo for listing directories and cache assets downloaded.

**Comment by HassanAbouelela** [comment]
I don't think version bumping is such a bad idea to be honest. I get wanting assets to go live immediately, but python-discord/branding#148 demonstrates some of the problems of having a non-locked dependency.

From my understanding of the issue, if that PR was merged right now, and we had automatic pulling of assets, quackstack would crash. I think that expecting two PRs in two different repos for one change is a lot yes, but that's preferable in my opinion to the suggested alternative.

That being said, there is another choice. Bring quackstack assets into this repo.

**Comment by jb3** [comment]
Quackstack assets into this repo does sound pretty alright.

**Comment by Shivansh-007** [comment]
There was a discussion in #dev-branding, where it was decided that:

- All `quackstack` assets would be moved to its repository.
- People will have to make 2 PRs if they want to add their accessories to `quackstack`.

**Comment by vcokltfre** [comment]
As of #25 all assets have been moved into the repo so I'm closing this issue now
