### ISSUE TITLE
Add GitHub Actions job for pushing semver release on release event

### ISSUE THREAD

**Issue by ks129** [python-discord/quackstack#24]
We can use a similar workflow as python-discord/olli uses for pushing versions. I want to do this myself because I have name ideas, but we need to have more actual code before.

**Comment by jb3** [comment]
We're not going to proceed with packaging Quackstack at this point. Integrations such as Sir Lancebot and potentially a CLI in future will call out to the publicly hosted instance at quackstack.pythondiscord.com.
