### ISSUE TITLE
Switch random generation to use HSV over RGB

### ISSUE THREAD

**Issue by vcokltfre** [python-discord/quackstack#26]
joe:
> for random duckies I'm tempted to say we should go with colorsys hsv/hsl because it gets nicer colours

I'm personally not familiar at all with HSV, but if someone else wants to implement this to get nicer colour generation be my guest!

If you want an example of how this is done in a way that gets ideal duck colours, check out: https://github.com/python-discord/aaaaAAAA/blob/main/aaaaAAAA/procedural_duckies.py

**Comment by jb3** [comment]
[colorsys](https://docs.python.org/3/library/colorsys.html) is the module to use!

**Comment by Akarys42** [comment]
I quite like this implementation from the staff PyWeek submission
```py
def make_color(hue: float, dark_variant: bool) -> tuple[float, float, float]:
    saturation = 1
    lightness = random.uniform(.7, .85)

    # green and blue do not like high lightness, so we adjust this depending on how far from blue-green we are
    # hue_fix is the square of the distance between the hue and cyan (0.5 hue)
    hue_fix = (1 - abs(hue - 0.5))**2
    # magic fudge factors
    lightness -= hue_fix * 0.15
    if dark_variant:
        lightness -= hue_fix * 0.25
    saturation -= hue_fix * 0.1

    return hue, lightness, saturation
```
It can then be converted in RGB with `colorsys`.

**Comment by Shivansh-007** [comment]
I will go ahead and do this.
