### ISSUE TITLE
API: Generate a random man-duck with an optional seed.

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/quackstack#3]
Once https://github.com/python-discord/aaaaAAAA/issues/33 has been solved, the man-duck templates should be moved in here as well, and we should be able to generate a random man-duck the same way that we currently generate a normal duck. If the seed is the same, the colors should match that of the normal duck implementation.

**Comment by Shivansh-007** [comment]
python-discord/aaaaAAAA#57 resolves that issue, so this can be moved from Dreamland to v1.0.0.

**Comment by vcokltfre** [comment]
Implemented, closing
