### ISSUE TITLE
Set up a PyPI-friendly package to execute the CLI commands.

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/quackstack#7]
Combine the powers of #6 and #5, and create a Python package that can be installed with pip and used to create duckies.

The ultimate goal is that we want to be able to do `pip install quackstack` and then just run `quackstack` from the terminal to create a ducky. `quackstack --help` should tell us what arguments we can pass in, and we should be able to pass in seeds, choose between duck or man-duck, and whatever else we can do with the API and the CLI.

**Comment by Shivansh-007** [comment]
I think we can just keep this issue as making it a PyPI package as done in #52. The rest of issue i.e. making it a CLI tool is already included in issue #5. 

We have gone the highway the other way round and made the PyPI package first.

**Comment by jb3** [comment]
We're not going to proceed with packaging Quackstack at this point. Integrations such as Sir Lancebot and potentially a CLI in future will call out to the publicly hosted instance at quackstack.pythondiscord.com.
