### ISSUE TITLE
CI: Push package to PyPI on release

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/quackstack#8]
We should solve #7 first, of course.

Once this is ready, we can set up CI to release this via GitHub releases. That's a very convenient way to do releases.

**Comment by jb3** [comment]
python-discord/olli has a Docker & PyPI workflow that publishes a `:main` and `:<sha>` tag for every main push as well as a `:<semver>` (e.g. `:0.0.1`) and `:latest` tag on every release.

It also has environments and deploy approvals.

Workflow file: https://github.com/python-discord/olli/blob/main/.github/workflows/release.yml
In action: https://github.com/python-discord/olli/actions/runs/712545628

**Comment by jb3** [comment]
We're not going to proceed with packaging Quackstack at this point. Integrations such as Sir Lancebot and potentially a CLI in future will call out to the publicly hosted instance at quackstack.pythondiscord.com.
